"""Initial migration

Revision ID: 9df46746b17c
Revises: 
Create Date: 2025-09-30 21:23:22.426651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9df46746b17c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('link', sa.String(), nullable=False),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('published_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_timestamp', sa.Integer(), nullable=False),
    sa.Column('images', sa.JSON(), nullable=True),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', name='news_content_status'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_link'), 'news', ['link'], unique=True)
    op.create_table('news_links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('link', sa.String(), nullable=False),
    sa.Column('published_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', name='news_link_status'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_links_link'), 'news_links', ['link'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_news_links_link'), table_name='news_links')
    op.drop_table('news_links')
    op.drop_index(op.f('ix_news_link'), table_name='news')
    op.drop_table('news')
    # ### end Alembic commands ###
